---
title: "Density-dependence in predation rates"
description: |
  
preview: images/Christmas_tree_mizer.png
author:
  - name: Gustav Delius
    url: {}
date: 2022-12-23
twitter:
  site: "@mizer_model"
  creator: "@gustavdelius"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

In this blog post, we delve into the technicalities of altering the manner in which mizer models address the density dependence of predation rates. At present, mizer's approach significantly diverges from that of EcoSim. Mizer focuses on the predator's satiation to determine density dependence, while EcoSim emphasizes the protective behaviour exhibited by the prey. To facilitate a more comprehensive comparison between mizer and EcoSim models, it is worth exploring the possibility of incorporating prey protective behaviour into the mizer framework.

The blog post is structured as follows: 
We first summarise the current way in which satiation is implemented in
mizer via the concept of a "feeding level". Then we discuss how protective
prey behaviour can be implemented in a perfectly analogous manner by
introducing the concept of a "vulnerability level". In an aside, we describe
a way how such a vulnerability level can arise from the protective behaviour
of prey individuals, modelled on the mechanism described in [@walters_structuring_1997]. We then provide the code necessary to instruct
mizer to switch from implementing predator satiation to implementing 
prey protection.


## Satiation and feeding level

Mizer implements satiation by imposing a maximum intake rate $h_i(w)$ for predators of species $i$ and size $w$. This leads to a feeding level $$
f_i(w)=\frac{E_i(w)}{E_i(w)+h_i(w)},
$$ where $E_i(w)$ is the encounter rate. The feeding level is a number between $0$ and $1$ where $0$ means that the predator eats everything it encounters and $1$ means that it feeds at the maximum intake rate. More generally, the consumption rate of an individual predator is $$
(1-f_i(w))E_i(w) = \frac{E_i(w)h_i(w)}{E_i(w)+h_i(w)} = f_i(w)h_i(w).
$$

This consumption by the predators imposes a predation mortality on the prey:
$$
\mu_{p.j}(w_p) = \sum_i\int dw\,(1-f_i(w))\phi_i(w,w_p)\gamma_i(w)N_i(w)\theta_{ij}.
$$

Note the predator abundance factor $N_i(w)$ in the expression for the per-capita predation mortality. Thus, while satiation imposes a limit on how far predation by an individual predator can grow if the abundance of prey increases, the predation mortality of the prey is still unbounded. The predation mortality of the prey actually grows more than linearly with the abundance of predators, because as the number of predators grows, the number of prey decreases, which decreases the encounter rate and hence the feeding level, thereby increasing the per-capita mortality.

## Protection and vulnerability level

The protective behaviour of prey can be modelled in a perfectly analogous
way to the satiation of predators, as we will now describe.

Instead of imposing a limit $h_i(w)$ on the consumption of an individual predator we can impose a limit $\mu_{max.j}(w_p)$ on the predation mortality of an individual prey of species $j$ and size $w_p$, so that no matter how much the abundance of predators is increased, the per-capita predation mortality never exceeds $\mu_{max.j}(w_p)$. This could for example arise from protective behaviour of the prey, like hiding in refuges or schooling.

In close analogy to how we introduced the feeding level above, we now introduce a vulnerability level
$$
\pi_j(w_p) = \frac{\mu_j(w_p)}{\mu_j(w_p) + \mu_{max.j}(w_p)},
$$
where $\mu_j(w_p)$ is the standard mizer predation mortality rate.

The modified predation mortality rate on a prey of species $j$ and weight $w_p$ is then
$$
(1-\pi_j(w_p))\mu_j(w_p) = 
\frac{\mu_j(w_p)\mu_{max.j}(w_p)}{\mu_j(w_p) + \mu_{max.j}(w_p)} =
\pi_j(w_p)\mu_{max.j}(w_p).
$$
The factor $(1-\pi_j(w_p))$ can be interpreted as the fraction of the prey that
are vulnerable to predation.

The encounter rate at which a predator of species $i$ and weight $w$ encounters prey is now
$$
E_i(w) = \gamma_i(w) 
\sum_j\int dw_p\,\phi_i(w, w_p)\theta_{ij}w_p(1-\pi_j(w_p))N_j(w_p).
$$

We see that protection of the prey does not put an upper limit on the encounter rate for predators, because this is still linear in the density of prey. 

### Mechanism for limit on mortality rate

[@walters_structuring_1997] suggest a simple mechanistic model for how the limit on predation mortality can arise. You should skip this section if you are only interested in how to include the limit on mortality rate in the mizer model. Its mechanistic origin will not be modelled explicitly in mizer. I present it here only for the curious.

[@walters_structuring_1997] assume that prey move between a protected and a vulnerable state. Only in the vulnerable state does a prey experiences predation mortality. In the protected state it experiences no mortality. The effective per-capita rate of predation mortality is thus lowered by a factor equal to the proportion of the prey that are vulnerable. Predation mortality, by acting only on the vulnerable, has the effect of reducing this proportion. As the number of predators increases, the proportion of vulnerable prey decreases. Therefore the effective predation mortality no longer grows linearly with the number of predators.

Let us now see how this mechanism plays out in detail. Let us denote by $V_j(w_p)$ the abundance density of vulnerable individuals. Then $N_j(w_p)-V_j(w_p)$ is the abundance density of protected individuals. We introduce a rate $\nu_j(w_p)$ at which protected individuals move between the protected and the vulnerable state. The rate of change in the abundance of vulnerable individuals is
$$
\frac{dV}{dt}=\nu\left(N-V\right)
-\nu V-\mu V.
$$
The first term of the right hand side represents individuals moving from the protected state to the vulnerable state at rate $\nu$ and the second term the opposite movement from vulnerable to protected at rate $\lambda\nu$. The third term represents the mortality of vulnerable individuals. Because all terms above are for the species and size we save space by not indicating the species index $j$ and the size $w_p$ on each term.

We now assume that this process of moving between states is fast enough so that it stays close to the steady state solution where $dV/dt=0$. At this steady state we have
$$
V = \frac{\nu}{2\nu+\mu}N 
= \frac{1}{2}\frac{\mu_{max}}{\mu + \mu_{max}}N
$$

where we have introduced $\mu_{max}=2\nu$.

In terms of the vulnerability level
$$
\pi = \frac{\mu}{\mu + \mu_{max}}
$$
we can rewrite the above as
$$
V = (1-\pi)\frac{1}{2}N.
$$

The rate at which a predator of species $i$ and weight $w$ encounters prey is now
$$
E_i(w) = \gamma_i(w) 
\sum_j\int dw_p\,\phi_i(w, w_p)\theta_{ij}w_pV_j(w_p),
$$
which differs from the standard mizer expression in replacing $N_j(w_p)$ by $V_j(w_p)$ because the predator only encounters the vulnerable individuals. Expressing this back in terms of $N$ gives
$$
E_i(w) = \gamma_i(w) 
\sum_j\int dw_p\,\phi_i(w, w_p)\frac{\theta_{ij}}{2}w_p(1-\pi_j(w_p))N_j(w_p).
$$

The factor of $1/2$ in the interaction matrix comes from the fact that each predator only spends half its time in the vulnerable state. 

## Implementation in mizer

